"""
Weekly Intelligence Brief generator using Jinja2 templates.
Produces a structured markdown report from the DB contents.
"""
from datetime import datetime, timezone, timedelta
from pathlib import Path
from jinja2 import Environment, BaseLoader
from src.db import get_recent_items, get_latest_trends, get_connection
from src.output.llm_synthesis import synthesize_implications

OUTPUT_DIR = Path(__file__).parent.parent.parent / "data" / "briefs"

BRIEF_TEMPLATE = """\
# Luxury Fashion Competitive Intelligence Brief
**Generated:** {{ generated_at }}
**Period:** Last 30 days | **Brands monitored:** Chanel, Dior, Gucci

---

## Executive Summary

{% if top_trends %}
The past week saw notable competitive activity across the luxury fashion landscape.
{% for t in top_trends[:3] %}
- **{{ t.competitor }}** showed a surge in **{{ t.event_type | replace('_', ' ') | title }}** activity (trend score: {{ "%.2f"|format(t.trend_score) }}, {{ t.count_7d }} articles in 7 days across {{ t.unique_sources }} sources).
{% endfor %}
{% else %}
No significant trend bursts detected in the current period. Activity remains at baseline levels.
{% endif %}

---

## Top Competitor Moves

{% for brand in brands %}
### {{ brand }}
{% set brand_events = events_by_brand[brand] %}
{% if brand_events %}
{% for ev in brand_events[:3] %}
**[{{ ev.event_type | replace('_', ' ') | title }}]** {{ ev.title }}
_{{ ev.source_name }} · {{ ev.published_at[:10] if ev.published_at else 'N/A' }} · Impact: {{ ev.impact_score }}/5_
{{ ev.summary }}

{% endfor %}
{% else %}
_No significant events detected for {{ brand }} in this period._
{% endif %}
{% endfor %}

---

## Emerging Trends

{% if emerging_trends %}
| Brand | Event Type | Trend Score | 7d Count | Sources |
|-------|-----------|-------------|----------|---------|
{% for t in emerging_trends %}
| {{ t.competitor }} | {{ t.event_type | replace('_', ' ') | title }} | {{ "%.2f"|format(t.trend_score) }} | {{ t.count_7d }} | {{ t.unique_sources }} |
{% endfor %}
{% else %}
_No emerging trends detected above threshold._
{% endif %}

---

## Critical Events

{% if critical_events %}
{% for ev in critical_events %}
> **{{ ev.competitor }} — {{ ev.event_type | replace('_', ' ') | title }}**
> {{ ev.evidence_snippet }}
> _Source: {{ ev.source_name }} · Impact: {{ ev.impact_score }}/5_

{% endfor %}
{% else %}
_No critical single-event signals this period._
{% endif %}

---

## Strategic Implications

{% if synthesis_by_brand %}
{% for brand in brands %}
{% if synthesis_by_brand.get(brand) %}
### {{ brand }}

{{ synthesis_by_brand[brand] }}

{% endif %}
{% endfor %}
_Synthesis generated locally by {{ synthesis_model }}._
{% else %}
{% for implication in implications %}
- {{ implication }}
{% endfor %}
{% if not implications %}
- Monitor Dior and Gucci for collection launch activity heading into next fashion week.
- Chanel's official communications remain the highest-confidence signal source.
{% endif %}
{% endif %}

---

## Source Coverage

| Source | Articles |
|--------|---------|
{% for src, count in source_counts.items() %}
| {{ src }} | {{ count }} |
{% endfor %}

---

## Source Links

{% for ev in recent_events[:20] %}
- [{{ ev.title[:80] }}]({{ ev.source_url }}) — {{ ev.competitor }} · {{ ev.published_at[:10] if ev.published_at else '' }}
{% endfor %}

---
_Generated by AI Competitive Intelligence Copilot · {{ generated_at }}_
"""


def _build_implications(events_by_brand: dict, trends: list[dict]) -> list[str]:
    implications = []
    brands = list(events_by_brand.keys())

    # Check for brands with no activity
    for brand in brands:
        if not events_by_brand[brand]:
            implications.append(
                f"{brand} has minimal coverage this period — possible quiet phase or monitoring gap."
            )

    # Detect if one brand is dominating campaign activity vs others
    campaign_brands = {
        t["competitor"] for t in trends
        if t["event_type"] == "campaign_or_collaboration"
    }
    for brand in brands:
        if brand in campaign_brands:
            others = [b for b in brands if b != brand and b not in campaign_brands]
            if others:
                implications.append(
                    f"{brand} is leading in campaign/collaboration activity. "
                    f"{', '.join(others)} may face a visibility gap."
                )

    # Reputational alerts
    rep_brands = {
        ev["competitor"] for evlist in events_by_brand.values()
        for ev in evlist
        if ev.get("event_type") == "reputational_issue" and (ev.get("impact_score") or 0) >= 3
    }
    for brand in rep_brands:
        implications.append(
            f"⚠ {brand} has reputational signals that warrant monitoring this week."
        )

    # Sentiment-based signals: use avg_sentiment from trends when available
    brand_sentiments: dict[str, list[float]] = {b: [] for b in brands}
    for t in trends:
        s = t.get("avg_sentiment")
        if s is not None and t["competitor"] in brand_sentiments:
            brand_sentiments[t["competitor"]].append(s)

    # Fall back to per-event sentiment if no trend-level data
    for brand, evlist in events_by_brand.items():
        if not brand_sentiments[brand]:
            scores = [ev["sentiment_score"] for ev in evlist if ev.get("sentiment_score") is not None]
            brand_sentiments[brand] = scores

    brand_avg_sentiment = {
        b: sum(scores) / len(scores)
        for b, scores in brand_sentiments.items()
        if scores
    }

    for brand, avg_s in brand_avg_sentiment.items():
        if avg_s < -0.2:
            implications.append(
                f"⚠ {brand} faces a reputational headwind: average media sentiment is negative "
                f"({avg_s:+.2f}). Monitor for escalating coverage."
            )
        elif avg_s > 0.4:
            others = [b for b in brands if b != brand]
            implications.append(
                f"{brand} leads in positive share-of-voice this week (avg sentiment {avg_s:+.2f}), "
                f"outpacing {' and '.join(others)} in favorable coverage."
            )

    if not implications:
        implications.append(
            "Activity is broadly distributed — no single brand dominates the signal landscape this period."
        )

    return implications


def generate_brief(use_llm: bool = True) -> str:
    now = datetime.now(timezone.utc)
    generated_at = now.strftime("%Y-%m-%d %H:%M UTC")
    brief_date = now.strftime("%Y-%m-%d")

    recent = get_recent_items(days=30)
    trends = get_latest_trends(limit=30)

    brands = ["Chanel", "Dior", "Gucci"]

    # Deduplicate by item_id (LEFT JOIN may produce multiple rows)
    seen: set[str] = set()
    unique_items: list[dict] = []
    for row in recent:
        if row["item_id"] not in seen:
            seen.add(row["item_id"])
            unique_items.append(row)

    # Group by brand, sort by impact
    events_by_brand: dict[str, list[dict]] = {b: [] for b in brands}
    for item in unique_items:
        brand = item.get("competitor")
        if brand in events_by_brand and item.get("impact_score"):
            events_by_brand[brand].append(item)
    for brand in brands:
        events_by_brand[brand].sort(key=lambda x: x.get("impact_score") or 0, reverse=True)

    emerging_trends = [t for t in trends if not t["is_critical"]]
    critical_trends = [t for t in trends if t["is_critical"]]

    # Map critical trend events back to item evidence
    critical_events: list[dict] = []
    conn = get_connection()
    for t in critical_trends[:5]:
        row = conn.execute("""
            SELECT e.event_type, e.evidence_snippet, e.impact_score, i.source_name, i.source_url, i.title
            FROM events e JOIN items i ON e.item_id = i.item_id
            WHERE e.competitor = ? AND e.event_type = ?
            ORDER BY e.impact_score DESC LIMIT 1
        """, (t["competitor"], t["event_type"])).fetchone()
        if row:
            ev = dict(row)
            ev["competitor"] = t["competitor"]
            critical_events.append(ev)
    conn.close()

    source_counts: dict[str, int] = {}
    for item in unique_items:
        sn = item.get("source_name", "Unknown")
        source_counts[sn] = source_counts.get(sn, 0) + 1
    source_counts = dict(sorted(source_counts.items(), key=lambda x: -x[1]))

    implications = _build_implications(events_by_brand, trends)

    # Per-brand LLM synthesis (graceful fallback if Ollama unreachable or disabled)
    synthesis_by_brand: dict[str, str] = {}
    synthesis_model = ""
    if use_llm:
        from src import config as _cfg
        synthesis_model = _cfg.OLLAMA_MODEL
        for brand in brands:
            print(f"[Brief] Synthesizing implications for {brand}…")
            text = synthesize_implications(
                brand=brand,
                events=events_by_brand.get(brand, []),
                trends=trends,
                brief_date=brief_date,
            )
            if text:
                synthesis_by_brand[brand] = text
        if not synthesis_by_brand:
            print("[Brief] LLM synthesis unavailable — using rule-based implications.")
            synthesis_model = ""

    env = Environment(loader=BaseLoader(), trim_blocks=True, lstrip_blocks=True)
    template = env.from_string(BRIEF_TEMPLATE)
    brief_md = template.render(
        generated_at=generated_at,
        brands=brands,
        top_trends=sorted(trends, key=lambda t: t["trend_score"], reverse=True)[:5],
        events_by_brand=events_by_brand,
        emerging_trends=emerging_trends[:10],
        critical_events=critical_events,
        implications=implications,
        synthesis_by_brand=synthesis_by_brand,
        synthesis_model=synthesis_model,
        source_counts=source_counts,
        recent_events=unique_items,
    )

    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    filename = OUTPUT_DIR / f"brief_{now.strftime('%Y%m%d_%H%M')}.md"
    filename.write_text(brief_md, encoding="utf-8")
    print(f"[Brief] Saved to {filename}")
    return brief_md
