"""
Local LLM brief synthesis via Ollama.

Replaces deterministic rule-based "strategic implications" with a 3-paragraph
narrative (positioning / risk / opportunity) generated by a locally-served
Llama 3.1 8B Instruct model. No paid API; requires `ollama serve` running.

Returns None on any failure so the caller can fall back to the rule-based path.
"""
import hashlib
import json

from src import config
from src.db import get_cached_synthesis, cache_synthesis

SYSTEM_PROMPT = (
    "You are a competitive intelligence analyst for luxury fashion houses "
    "(Chanel, Dior, Gucci). Write tight, executive-level strategic implications. "
    "No filler. No hedging. No headers, no bullet lists. "
    "Exactly three short paragraphs, in this order:\n"
    "  (1) Positioning — what the brand's recent moves say about its strategy.\n"
    "  (2) Risk — the strongest threat signal in the data.\n"
    "  (3) Opportunity — one concrete move the brand could make this quarter.\n"
    "Each paragraph 2-4 sentences. Reference specific events when useful. "
    "Do not invent facts beyond what is provided."
)


def _build_user_prompt(brand: str, events: list[dict], trends: list[dict]) -> str:
    competitors = [b for b in ("Chanel", "Dior", "Gucci") if b != brand]
    lines = [
        f"Brand: {brand}",
        f"Competitor set: {', '.join(competitors)}",
        "",
        f"Recent events ({len(events)}):",
    ]
    for ev in events[:8]:
        etype = (ev.get("event_type") or "unknown").replace("_", " ")
        impact = ev.get("impact_score") or 0
        title = (ev.get("title") or "").strip()[:140]
        snippet = (ev.get("evidence_snippet") or ev.get("summary") or "").strip()[:200]
        lines.append(f"- [{etype}, impact={impact}/5] {title} — {snippet}")
    if not events:
        lines.append("- (none above threshold)")

    lines.append("")
    brand_trends = [t for t in trends if t.get("competitor") == brand]
    lines.append(f"Detected trends for {brand} ({len(brand_trends)}):")
    for t in brand_trends[:6]:
        theme = (t.get("event_type") or "").replace("_", " ")
        z = t.get("burst_z") or 0
        s = t.get("unique_sources") or 0
        score = t.get("trend_score") or 0
        lines.append(
            f"- {theme}: trend_score={score:.2f}, burst_z={z:.2f}, sources={s}"
        )
    if not brand_trends:
        lines.append("- (no trends above threshold)")

    lines.append("")
    lines.append("Write the three paragraphs now.")
    return "\n".join(lines)


def _prompt_hash(brand: str, prompt: str) -> str:
    h = hashlib.sha256()
    h.update(config.OLLAMA_MODEL.encode("utf-8"))
    h.update(b"\x00")
    h.update(brand.encode("utf-8"))
    h.update(b"\x00")
    h.update(prompt.encode("utf-8"))
    return h.hexdigest()


def _call_ollama(prompt: str) -> str | None:
    try:
        import httpx
    except ImportError:
        print("[LLM] httpx not installed — skipping synthesis")
        return None

    payload = {
        "model": config.OLLAMA_MODEL,
        "prompt": prompt,
        "system": SYSTEM_PROMPT,
        "stream": False,
        "options": {
            "temperature": config.OLLAMA_TEMPERATURE,
            "seed": config.OLLAMA_SEED,
        },
    }
    try:
        with httpx.Client(timeout=config.OLLAMA_TIMEOUT) as client:
            resp = client.post(f"{config.OLLAMA_HOST}/api/generate", json=payload)
            resp.raise_for_status()
            data = resp.json()
    except httpx.ConnectError:
        print(f"[LLM] Ollama not reachable at {config.OLLAMA_HOST} — falling back")
        return None
    except httpx.TimeoutException:
        print(f"[LLM] Ollama timed out after {config.OLLAMA_TIMEOUT}s — falling back")
        return None
    except Exception as e:
        print(f"[LLM] Ollama call failed: {e} — falling back")
        return None

    text = (data.get("response") or "").strip()
    if not text:
        print("[LLM] Empty response from Ollama — falling back")
        return None
    return text


def synthesize_implications(
    brand: str,
    events: list[dict],
    trends: list[dict],
    brief_date: str,
) -> str | None:
    """Generate 3-paragraph strategic narrative for a brand. Returns None on failure."""
    if not config.LLM_SYNTHESIS_ENABLED:
        return None

    prompt = _build_user_prompt(brand, events, trends)
    phash = _prompt_hash(brand, prompt)

    cached = get_cached_synthesis(brand, phash)
    if cached:
        return cached

    output = _call_ollama(prompt)
    if not output:
        return None

    try:
        cache_synthesis(
            brand=brand,
            brief_date=brief_date,
            model=config.OLLAMA_MODEL,
            prompt_hash=phash,
            output=output,
        )
    except Exception as e:
        print(f"[LLM] Cache write failed (non-fatal): {e}")

    return output
